// Generated by LiveScript 1.4.0
(function(){
  var history_pages, history_visits, exports;
  history_pages = require('./Schema/history_pages');
  history_visits = require('./Schema/history_visits');
  exports = module.exports = function(app){
    app.post('/log_history_pages', function(req, res){
      var body;
      body = req.body;
      return history_pages.create(body, function(err, res2){
        return res.send('');
      });
    });
    return app.post('/log_history_visits', function(req, res){
      var body;
      body = req.body;
      return history_visits.create(body, function(err, res2){
        return res.send('');
      });
    });
  };
}).call(this);
